config/routes.rb
CompanyManager::Application.routes.draw do

  resources :activities
	resources :campaigns
	resources :campaign_types
	resources :clients
	resources :companies
	resources :departments
	resources :employees
	resources :menus
	resources :project_statuses
	resources :projects
	resources :sales
	resources :schedules
	resources :schedule_blocks
	resources :todos
	resources :users
	resources :user_sessions

	match 'settings' => 'settings#index'
	match 'dashboard' => 'dashboard#index'
	match 'dashboard/people' => 'dashboard#people'
	match 'dashboard/projects' => 'dashboard#projects'
	match 'dashboard/reports' => 'dashboard#reports'

	match 'login' => 'user_sessions#new', :as => 'login'
	match 'logout' => 'user_sessions#destroy', :as => 'logout'

  root :to => "dashboard#index"

end

app/controllers/project_statuses_controller.rb
class ProjectStatusesController < ApplicationController
  # GET /project_statuses
  # GET /project_statuses.xml
  def index
    @project_statuses = ProjectStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @project_statuses }
    end
  end

  # GET /project_statuses/1
  # GET /project_statuses/1.xml
  def show
    @project_status = ProjectStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project_status }
    end
  end

  # GET /project_statuses/new
  # GET /project_statuses/new.xml
  def new
    @project_status = ProjectStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project_status }
    end
  end

  # GET /project_statuses/1/edit
  def edit
    @project_status = ProjectStatus.find(params[:id])
  end

  # POST /project_statuses
  # POST /project_statuses.xml
  def create
    @project_status = ProjectStatus.new(params[:project_status])

    respond_to do |format|
      if @project_status.save
        format.html { redirect_to(@project_status, :notice => 'Project status was successfully created.') }
        format.xml  { render :xml => @project_status, :status => :created, :location => @project_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /project_statuses/1
  # PUT /project_statuses/1.xml
  def update
    @project_status = ProjectStatus.find(params[:id])

    respond_to do |format|
      if @project_status.update_attributes(params[:project_status])
        format.html { redirect_to(@project_status, :notice => 'Project status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /project_statuses/1
  # DELETE /project_statuses/1.xml
  def destroy
    @project_status = ProjectStatus.find(params[:id])
    @project_status.destroy

    respond_to do |format|
      format.html { redirect_to(project_statuses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/project_statuses_helper.rb
module ProjectStatusesHelper
end

app/views/project_statuses/_form.html.haml
- form_for(@project_status) do |f|
	- if @project_status.errors.any?
		#error_explanation
			%h2
				! #{pluralize(@project_status.errors.count, "error")} prohibited this project_status from being saved:
			%ul
				- @project_status.errors.full_messages.each do |msg|
					%li= msg

	%fieldset
		%legend Project Status Details

		%dl
			%dt= f.label :title
			%dd= f.text_field :title

		%dl
			%dt= f.label :type
			%dd= f.text_field :type

		%dl
			%dt= f.label :ordering
			%dd= f.text_field :ordering

	%fieldset
		.actions
			= f.submit

app/views/project_statuses/edit.html.haml
%article
	%h1 Editing project_status

	= render 'form'

	! #{link_to 'Show', @project_status} | #{link_to 'Back', project_statuses_path}

app/views/project_statuses/index.html.haml
%article
	%h1 Project Statuses

	%table.datalist
		%thead
			%tr
				%th Title
				%th Type
				%th Ordering

		%tbody
			- @project_statuses.each do |project_status|
				%tr
					%td= project_status.title
					%td= project_status.type
					%td= project_status.ordering
					%td= link_to 'Show', project_status
					%td= link_to 'Edit', edit_project_status_path(project_status)
					%td= link_to 'Destroy', project_status, :confirm => 'Are you sure?', :method => :delete

	= link_to 'New Project status', new_project_status_path

app/views/project_statuses/new.html.haml
%article
	%h1 New Project Status
	= render 'form'
	= link_to 'Back', project_statuses_path

app/views/project_statuses/show.html.haml
%article
	%p#notice= notice

	%p
		%b Title:
		= @project_status.title

	%p
		%b Type:
		= @project_status.type

	%p
		%b Ordering:
		= @project_status.ordering

	%p
		! #{link_to 'Edit', edit_project_status_path(@project_status)} | #{link_to 'Back', project_statuses_path}