config/routes.rb
CompanyManager::Application.routes.draw do

  resources :activities
	resources :campaigns
	resources :campaign_types
	resources :clients
	resources :companies
	resources :departments
	resources :employees
	resources :menus
	resources :project_statuses
	resources :projects
	resources :sales
	resources :schedules
	resources :schedule_blocks
	resources :todos
	resources :users
	resources :user_sessions

	match 'settings' => 'settings#index'
	match 'dashboard' => 'dashboard#index'
	match 'dashboard/people' => 'dashboard#people'
	match 'dashboard/projects' => 'dashboard#projects'
	match 'dashboard/reports' => 'dashboard#reports'

	match 'login' => 'user_sessions#new', :as => 'login'
	match 'logout' => 'user_sessions#destroy', :as => 'logout'

  root :to => "dashboard#index"

end

app/models/schedule.rb
# == Schema Information
# Schema version: 20110219231503
#
# Table name: schedules
#
#  id         :integer         not null, primary key
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#

class Schedule < ActiveRecord::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.xml
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully created.') }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<legend>Schedule Details</legend>
		
		<dl>
			<dt><%= f.label :date %></dt>
    	<dd><%= f.date_select :date %></dd>
		</dl>
	</fieldset>
	
	<fieldset>
		<div class="actions">
    	<%= f.submit %>
  	</div>
	</fieldset>
<% end %>

app/views/schedules/edit.html.erb
<article>
	<h1>Editing schedule</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @schedule %> |
	<%= link_to 'Back', schedules_path %>
</article>

app/views/schedules/index.html.erb
<article>
	<h1>Listing schedules</h1>

	<table class="datalist">
		<thead>
			<tr>
				<th>Date</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
		<% @schedules.each do |schedule| %>
			<tr>
				<td><%= schedule.date %></td>
				<td>
					<%= link_to 'S', schedule %>,
					<%= link_to 'E', edit_schedule_path(schedule) %>,
					<%= link_to 'D', schedule, :confirm => 'Are you sure?', :method => :delete %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>

	<br />

	<%= link_to 'New Schedule', new_schedule_path %>
</article>

app/views/schedules/new.html.erb
<article>
	<h1>New schedule</h1>

	<%= render 'form' %>

	<%= link_to 'Back', schedules_path %>
</article>

app/views/schedules/show.html.erb
<article>
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Date:</b>
	  <%= @schedule.date %>
	</p>


	<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
	<%= link_to 'Back', schedules_path %>
</article>