config/routes.rb
CompanyManager::Application.routes.draw do

  resources :activities
	resources :campaigns
	resources :campaign_types
	resources :clients
	resources :companies
	resources :departments
	resources :employees
	resources :menus
	resources :project_statuses
	resources :projects
	resources :sales
	resources :schedules
	resources :schedule_blocks
	resources :todos
	resources :users
	resources :user_sessions

	match 'settings' => 'settings#index'
	match 'dashboard' => 'dashboard#index'
	match 'dashboard/people' => 'dashboard#people'
	match 'dashboard/projects' => 'dashboard#projects'
	match 'dashboard/reports' => 'dashboard#reports'

	match 'login' => 'user_sessions#new', :as => 'login'
	match 'logout' => 'user_sessions#destroy', :as => 'logout'

  root :to => "dashboard#index"

end

app/models/project.rb
# == Schema Information
# Schema version: 20110219231503
#
# Table name: projects
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  due_date        :date
#  start_date      :date
#  completion_date :date
#  status          :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Project < ActiveRecord::Base
  attr_accessible :name, :due_date, :start_date, :completion_date, :status_id, :manager_id

  default_scope :order => :name

  belongs_to :manager, :class_name => 'Employee'
  #belongs_to :status

  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_user

  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    @managers = Employee.department "Sales"
    @statuses = Status.group 2

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @managers = Employee.department "Sales"
    @statuses = Status.group 2
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
 	<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<legend>Project Details</legend>

		<dl>
			<dt><%= f.label :name %></dt>
			<dd><%= f.text_field :name %></dd>
		</dl>

		<dl>
			<dt><%= f.label :manager_id %></dt>
			<dd><%= collection_select(:project, :manager_id, @managers, :id, :fullname, options = { :prompt => "-Select a project manager"}) %></dd>
		</dl>

		<dl>
			<dt><%= f.label :due_date %></dt>
    	<dd><%= f.date_select :due_date %></dd>
		</dl>

		<dl>
    	<dt><%= f.label :start_date %></dt>
    	<dd><%= f.date_select :start_date %></dd>
		</dl>

		<dl>
    	<dt><%= f.label :completion_date %></dt>
    	<dd><%= f.date_select :completion_date %></dd>
		</dl>

		<dl>
			<dt><%= f.label :status %></dt>
   		<dd><%= collection_select(:project, :status_id, @statuses, :id, :title, options = { :prompt => "- Select the current status" })%></dd>
		</dl>
	</fieldset>

	<fieldset>
    <%= f.submit %>
	</fieldset>
<% end %>

app/views/projects/edit.html.haml
%article
	%h1 Editing project

	= render 'form'

	= link_to 'Show', @project
	|
	=link_to('Back', projects_path)

app/views/projects/index.html.haml
%article
	%h1 Listing projects

	%table.datalist
		%thead
			%tr
				%th Name
				%th{ :width => 100 } Status

		%tbody
			- @projects.each do |project|
				%tr
					%td
						= link_to project.name, project
						%small.hover
							= link_to 'Edit', edit_project_path(project)
							= link_to 'Delete', project, :confirm => 'Are you sure?', :method => :delete
					-#%td= project.status.title if project.status

	= link_to 'New Project', new_project_path

app/views/projects/new.html.erb
<article>
	<h1>New project</h1>
	
	<%= render 'form' %>
	<%= link_to 'Back', projects_path %>
</article>

app/views/projects/show.html.haml
%article.clearfix
	%h1
		= @project.name
		%div.actions
			%div= link_to 'Edit', edit_project_path(@project)
			%div= link_to 'Back', projects_path

	- if notice
		%div#notice= notice

	%fieldset
		%legend Project Details

		.unit.size1of2
			%p
				= "Due: #{@project.due_date}"

		.unit.size1of2.lastunit
			- if @project.status
				%p
					! Status: #{@project.status.title}

		.unit.size1of2
			- if @project.manager
				%p
					! Managed by: #{link_to @project.manager.fullname, @project.manager }

	.line
		.unit.size2of3
			%section.module.subtle
				.inner
					.title Notes
					.body
						= render 'project_notes/widget'
					.footer
						= link_to "More...", projects_path
			%section.module.subtle
				.inner
					.title still add
					.body
						%ul
							%li stuff
							%li key dates - milestones
					.footer
		.unit.size1of3.lastunit
			%section.module.subtle
				.inner
					.title Tasks
					.body
						= render 'activities/widget'
					.footer
						= link_to "More...", activities_path

			%section.module.subtle
				.inner
					.title Time Distribution
					.body
						<img src="http://chart.apis.google.com/chart?chs=197x150&cht=p3&chco=299900&chd=s:GJRH&chdl=Sales|Design|Development|Finalization&chts=676767,12" alt="Time Distubution" />
					.footer