config/routes.rb
CompanyManager::Application.routes.draw do

  resources :activities
	resources :campaigns
	resources :campaign_types
	resources :clients
	resources :companies
	resources :departments
	resources :employees
	resources :menus
	resources :project_statuses
	resources :projects
	resources :sales
	resources :schedules
	resources :schedule_blocks
	resources :todos
	resources :users
	resources :user_sessions

	match 'settings' => 'settings#index'
	match 'dashboard' => 'dashboard#index'
	match 'dashboard/people' => 'dashboard#people'
	match 'dashboard/projects' => 'dashboard#projects'
	match 'dashboard/reports' => 'dashboard#reports'

	match 'login' => 'user_sessions#new', :as => 'login'
	match 'logout' => 'user_sessions#destroy', :as => 'logout'

  root :to => "dashboard#index"

end

app/models/sale.rb
# == Schema Information
# Schema version: 20110219231503
#
# Table name: sales
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  amount     :float
#  close_date :date
#  created_at :datetime
#  updated_at :datetime
#

class Sale < ActiveRecord::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  # GET /sales
  # GET /sales.xml
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.xml
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.xml
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.xml
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to(@sale, :notice => 'Sale was successfully created.') }
        format.xml  { render :xml => @sale, :status => :created, :location => @sale }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.xml
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to(@sale, :notice => 'Sale was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.xml
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to(sales_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<legend>Sale Details</legend>
		
		<dl>
			<dt><%= f.label :name %></dt>
			<dd><%= f.text_field :name %></dd>
		</dl>
		<dl>
			<dt><%= f.label :amount %></dt>
			<dd><%= f.text_field :amount %></dd>
		</dl>
		<dl>
    	<dt><%= f.label :close_date %></dt>
    	<dd><%= f.date_select :close_date %></dd>
		</dl>
	</fieldset>
	
	<fieldset>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	</fieldset>
<% end %>

app/views/sales/edit.html.erb
<article>
	<h1>Editing sale</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @sale %> |
	<%= link_to 'Back', sales_path %>
</article>

app/views/sales/index.html.erb
<article>
	<h1>Listing sales</h1>

	<table class="datalist">
		<thead>
			<tr>
				<th>Name</th>
				<th>Amount</th>
				<th>Close date</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
		<% @sales.each do |sale| %>
			<tr>
				<td><%= sale.name %></td>
				<td><%= sale.amount %></td>
				<td><%= sale.close_date %></td>
				<td>
					<%= link_to 'S', sale %>,
					<%= link_to 'E', edit_sale_path(sale) %>,
				<%= link_to 'D', sale, :confirm => 'Are you sure?', :method => :delete %>
				</td>
			</tr>
		<% end %>
</table>

<%= link_to 'New Sale', new_sale_path %>
</article>

app/views/sales/new.html.erb
<article>
	<h1>New sale</h1>

	<%= render 'form' %>
	<%= link_to 'Back', sales_path %>
</article>

app/views/sales/show.html.erb
<article>
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @sale.name %>
	</p>

	<p>
	  <b>Amount:</b>
	  <%= @sale.amount %>
	</p>

	<p>
	  <b>Close date:</b>
	  <%= @sale.close_date %>
	</p>


	<%= link_to 'Edit', edit_sale_path(@sale) %> |
	<%= link_to 'Back', sales_path %>
</article>